server:
  port: 8081
spring:
  datasource:
    username: postgres
    password: a
    url: jdbc:postgresql://localhost:5432/ms-card
    driver-class-name: org.postgresql.Driver
#  liquibase:
#    change-log: liquibase/changelog-master.yml
#    enabled: true
#    drop-first: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create


